language: python
python:
 - 2.7
 - 3.3

env:
 - DJANGO_VERSION=1.4.20
 - DJANGO_VERSION=1.5.11
 - DJANGO_VERSION=1.6.8

install:
  - pip install -q Django==$DJANGO_VERSION coverage coveralls
  - pip install . --use-mirrors
  - pip install -r testproject/requirements.txt --use-mirrors

script:
  - coverage run testproject/manage.py test testproject wiki_core

after_success:
  - coverage report
  - coveralls


matrix:
    exclude:
        - python: 3.3
          env: DJANGO_VERSION=1.4.20
    include:
        - python: 2.7
          env: DJANGO_VERSION=1.7.1
        - python: 3.3
          env: DJANGO_VERSION=1.7.1
        - python: 3.4
          env: DJANGO_VERSION=1.7.1
